### ISSUE TITLE
Project standards?

### ISSUE THREAD

**Issue by BrainStone** [fivunlm/cppstreams#1]
Hi! I just stumbled across this project. I noticed you're having some issues with supporting a wide range of containers. And I think I stumbled across a solution that allows this to work with any container that supports `std::begin` and `std::end` (even arrays do!).  
I threw together a little example of that technique: http://cpp.sh/4nt7u

So I'd love to contribute to this project. So I was wondering if there are any standards I should be aware of, like for example the commit message style, etc.

There's a lot of other stuff I'd love to add too, so don't be surprised to see a few PRs ;)

Is there also a convinient way of contacting you?

Edit: Which C++ version is the minimum? C++14, C++11, C++98?  
(I'm hoping for anything but C++98 xD)

**Comment by BrainStone** [comment]
Here's an a lot more extensive example: http://cpp.sh/37aqs

As I said before it supports everything that supports `std::begin` and `std::end`. Which is arrays, containers that have `begin()` and `end()` methods or containes that specialized the template for `std::begin` and `std::end`. Only thing that's missing are the queue types like `std::queue` and `std::stack`. I'll try to make it work for them (and as many other similar containers as possible) too.

**Comment by fivunlm** [comment]
HI @BrainStone, sorry for the delay. Great idea! I've not much free time to put to this project so all help is welcome 😃 
C++11 should be the minimum :-)
I added you as collaborator
